# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-02 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171202_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='Title', max_length=33),
        ),
    ]
